spring.application.name=ProductApp


spring.datasource.url= jdbc:h2:mem:demo
spring.datasource.driverClassName= org.h2.Driver

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.show-sql=true
